### ISSUE TITLE
remove chrono dependency

### ISSUE THREAD

**Issue by coderedart** [greaka/arcdps_bindings#12]
when i run `cargo audit`, i get this error 
```
Crate:     time
Version:   0.1.45
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Severity:  6.2 (medium)
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.45
└── chrono 0.4.26
    └── arcdps 0.9.0
        └── jokolink 0.1.0
error: 1 vulnerability found!
```

chrono won't fix it https://github.com/chronotope/chrono/issues/602#issuecomment-1513811804 
and instead recommends people to wait for `0.5` release which has been going on since April https://github.com/chronotope/chrono/issues/970 . Just like the Alliances :D

So, we have three options:
1. wait for chrono `0.5` which might take a while
2. directly use `time` crate, if possible. 
3. feature gate the uses of chrono. AFAIK it is only used for combat messages. and they can be enabled by an optional feature

**Comment by greaka** [comment]
Chrono won't fix it because they aren't affected. As a result, I'm not in a hurry to fix it either. Feel free to open a PR though :slightly_smiling_face:

**Comment by pitdicker** [comment]
The plan for chrono is to release a 0.4 version soon (I hope within weeks) that drops the time 0.1 dependency. It has been part of the public API, that is why it took so long. But we don't believe making the switch now would cause real-world breakage.

**Comment by greaka** [comment]
`cargo update` fixes this issue
https://github.com/chronotope/chrono/releases/tag/v0.4.30
